swagger: "2.0"
info:
  description: "IdeaStockerについてのAPI"
  version: "1.0.0"
  title: "IdeaStocker API"
  termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  # /pet/{petId}:
  #   get:
  #     summary: "ペット情報API"
  #     description: "指定されたpetIdの情報を返します"
  #     parameters:
  #     - name: "petId"
  #       in: "path"
  #       description: "取得したいペットのID"
  #       required: true
  #       type: "integer"
  #       format: "int64"
  #     responses:
  #       200:
  #         description: "成功時のレスポンス"
  #         schema:
  #           type: "object"
  #           properties:
  #             id:
  #               type: "integer"
  #               format: "int64"
  #             name:
  #               type: "string"
  #               example: "doggie"
  /newidea:
    post:
      summary: "新規のアイデアをDBに追加する"
      parameters:
        - name: newIdea
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - idea
              properties:
                idea:
                  type: string
  /show:
    get:
      summary: "現在DBにあるアイデア一覧を返す"
  /show/notyet:
    get:
        summary: "statusがnotYetのアイデア一覧を返す"
  /shoe/nowdoing:
    get:
      summary: "statusがnowDoingのアイデア一覧を返す"
  /delete/{id}:
    get:
      summary: "DB内の指定のidのアイデアを削除"
  /change/{id}:
    get:
      summary: "指定のidのアイデアのステータスを変更"
  /create:
    get:
      summary: "テーブルideasを作成する"