openapi: 3.0.0

info:
  description: "IdeaStockerについてのAPI"
  version: "1.0.0"
  title: "IdeaStocker API"
  termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  # /pet/{petId}:
  #   get:
  #     summary: "ペット情報API"
  #     description: "指定されたpetIdの情報を返します"
  #     parameters:
  #     - name: "petId"
  #       in: "path"
  #       description: "取得したいペットのID"
  #       required: true
  #       type: "integer"
  #       format: "int64"
  #     responses:
  #       200:
  #         description: "成功時のレスポンス"
  #         schema:
  #           type: "object"
  #           properties:
  #             id:
  #               type: "integer"
  #               format: "int64"
  #             name:
  #               type: "string"
  #               example: "doggie"
  /newidea:
    post:
      summary: 新規のアイデアをDBに追加する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - idea
              properties:
                idea:
                  type: string
      responses:
        200:
            description: 正常に投稿できました
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    created_at:
                      type: time.Time
                    status:
                      type: string
                    idea:
                      type: string
  /show:
    get:
      summary: 現在DBにあるアイデア一覧を返す
      responses:
        200:
          description: 正常に取得できました
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: time.Time
                    status:
                      type: string
                    idea:
                      type: string
 
  /show/notyet:
    get:
      summary: "statusがnotYetのアイデア一覧を返す"
      responses:
        200:
          description: 正常に取得できました
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: time.Time
                    status:
                      type: string
                    idea:
                      type: string
  /show/nowdoing:
    get:
      summary: "statusがnowDoingのアイデア一覧を返す"
      responses:
        200:
          description: 正常に取得できました
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: time.Time
                    status:
                      type: string
                    idea:
                      type: string
  /delete/{id}:
    get:
      summary: "DB内の指定のidのアイデアを削除"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: 削除したいアイデアのid
      responses:
        200:
          description: 正常に削除されました
  /change/{id}:
    get:
      summary: "指定のidのアイデアのステータスを変更"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: ステータスを変更したいアイデアのid
      responses:
        200:
          description: 正常に変更できました
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: time.Time
                    status:
                      type: string
                    idea:
                      type: string
  /create:
    get:
      summary: "テーブルideasを作成する"